parse_config:
  zmk_combos:
    combo_bt0:
      align: left
    combo_bt1:
      align: right
  raw_binding_map:
    "&kp DE_Y": "Y"
    "&kp DE_Z": "Z"
    "&kp DE_SQT": "'"
    "&kp DE_COMMA": ","
    "&kp DE_DOT": "."
    "&kp DE_SLASH": "/"
    "&slash_qmark": {t: "/", s: "?"}
    "&kp DE_MINUS": "-"
    "&kp DE_PLUS": "+"
    "&kp DE_ASTRK": "*"
    "&kp DE_UNDER": "_"
    "&kp DE_CARET": "^"
    "&kp DE_EXCL": "!"
    "&kp DE_AT": "@"
    "&kp DE_HASH": "#"
    "&kp DE_DLLR": "$"
    "&kp DE_EQUAL": "="
    "&kp DE_LPAR": "("
    "&kp DE_RPAR": ")"
    "&kp DE_LBKT": "["
    "&kp DE_RBKT": "]"
    "&kp DE_BSLH": "\\"
    "&kp DE_LBRC": "{"
    "&kp DE_RBRC": "}"
    "&kp DE_LT": "<"
    "&kp DE_GT": ">"
